### ISSUE TITLE
update README to use BiocManager

### ISSUE THREAD

**Issue by LiNk-NY** [jstansfield0/multiHiCcompare#1]
Hi John, @jstansfield0

Please modify your `README.md` so that it uses `BiocManager`: 

```r
if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install(c("BiocParallel", "HiCcompare", "edgeR"))
```
Regards,
Marcel

**Comment by jstansfield0** [comment]
HI Marcel, @LiNk-NY,

I updated the README. However, I am having issues pushing upstream to bioconductor. I apparently do not have write access to the bioconductor git repository for the multiHiCcompare package.  But I do have access to my other package, HiCcompare. How can I fix this?

Thanks,
John

**Comment by LiNk-NY** [comment]
Hi John, @jstansfield0 

Please make sure you have `git@git.bioconductor.org:packages/multiHiCcompare.git` in the output of your `git remote -v` and that you are pushing to it. Please see: http://bioconductor.org/developers/how-to/git/new-package-workflow/

Regards,
Marcel
