### ISSUE TITLE
Cyclic loess sets entire bins to 0

### ISSUE THREAD

**Issue by chbk** [jstansfield0/multiHiCcompare#2]
Hi, I'm getting strange Hi-C matrices after cyclic loess normalization. Many adjacent bins get deleted.

"Before \ After" matrices and MD plots for 2 chromosomes normalized independently:

Chromosome 9:

![chr9](https://user-images.githubusercontent.com/7478535/53742702-8db6da00-3e99-11e9-8ae8-8f985379136c.png)

![md9](https://user-images.githubusercontent.com/7478535/53747215-14bc8000-3ea3-11e9-82ba-b064d336fe96.png)

Chromosome 15:

![chr15](https://user-images.githubusercontent.com/7478535/53742719-94dde800-3e99-11e9-9579-75c88683afc5.png)

![md15](https://user-images.githubusercontent.com/7478535/53747219-15edad00-3ea3-11e9-8697-35583d758039.png)

I ran this separately for each chromosome, with 2 conditions x 3 replicates each time:

```r
hicexp = make_hicexp(data_list=matrices, groups=c(1,1,1,2,2,2))
normalized = cyclic_loess(hicexp)
MD_hicexp(hicexp)
```

Can you help me pinpoint the issue?

**Comment by jstansfield0** [comment]
The heatmaps do look strange as they are not symmetric. I think something may be going wrong with filtering on your data. in the make_hicexp() command you can try setting `remove.regions = NULL` as it may be trying to filter out centromere regions incorrectly if you are not using hg19 data. You can also turn off filtering by average IF and zeros by setting `filter = FALSE` or adjust it using the `A.min` and `zero.p` options.

**Comment by chbk** [comment]
Thanks a lot! I get nice matrices with `remove.regions = NULL`.
