### ISSUE TITLE
Issue about make_hicexp

### ISSUE THREAD

**Issue by lazurite** [jstansfield0/multiHiCcompare#3]
Is the package suitable for drosophila melanogaster (dm3)? I tried to use the function make_hicexp and failed on the columns of chromosome (2L,2R here)  , the name of chromosome will became “NA”.

**Comment by jstansfield0** [comment]
It should work. Make sure your data is formatted correctly according to the vignettes and help file. Chromosome names should be numeric when you are entering them.
